gdb strops.bin \
  -ex "b *0x400795" \
  -ex "r" \
  -ex "set \$rax=\$rdx" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "set \$rax=\$rdx" \
  -ex "echo $rax" \
  -ex "c" \
  -ex "q"
